import { generateContentSafe, fileToPart, GEMINI_MODELS } from "./geminiClient";
import { SavedModel, Resolution, AspectRatio, BenchmarkAnalysisResult } from "../types";

/**
 * 1️⃣ Background Change Service
 * Handles: Presets (Studio, MZ Cafe), Custom, Persona Injection
 */
export const replaceBackground = async (
  baseImage: string,
  bgRefImage: string | null,
  userPrompt: string,
  options?: { 
    faceOptions?: any, 
    ambientMatch?: boolean, 
    modelPersona?: SavedModel, 
    styleReference?: boolean,
    resolution?: Resolution,
    aspectRatio?: AspectRatio
  }
) => {
  // 1. Build Prompts (Migrated from geminiService.ts)
  const parts: any[] = [];
  parts.push(fileToPart(baseImage));

  if (bgRefImage && bgRefImage.length > 100) {
    if (options?.styleReference) {
      console.log('Style Reference Mode: Analyzing image first...');
      // Logic for style reference extraction could go here, but for now we push ref image if needed
      // Actually per previous logic, if styleRef, we might handle differently.
      // But assuming simpler Custom BG for now:
       parts.push(fileToPart(bgRefImage));
    } else {
       parts.push(fileToPart(bgRefImage));
    }
  }

  let finalPrompt = userPrompt;
  const preset = options?.faceOptions?.preset;

  // [MODEL PERSONA INJECTION]
  if (options?.modelPersona) {
    const { description, faceRefImage } = options.modelPersona;
    finalPrompt += `\n\n[MODEL PERSONA (CRITICAL OVERRIDE)]`;
    finalPrompt += `\n**IDENTITY:** Must strictly match the facial features and body type of the provided reference.`;
    if (description) finalPrompt += `\n**DESCRIPTION:** ${description}`;
    if (faceRefImage) {
      parts.push(fileToPart(faceRefImage));
      finalPrompt += `\n**REFERENCE:** Use the provided Model Reference Image for the face and identity.`;
    }
  }

  // [PRESETS]
  if (preset === 'BASIC_STUDIO') {
      finalPrompt = `
Create a high-conversion lower-body fashion thumbnail optimized for e-commerce.

Focus on the pants only:
- Crop from waist to shoes
- Center the thighs, knees, and hemline clearly
- Maintain the original fit, color, and fabric texture of the pants with no color shift
- Natural standing pose, slight leg separation for clear silhouette
- Shoes fully visible and grounded on the floor

Background:
- Clean minimal studio background in soft off-white or light concrete gray
- Subtle natural shadow under the shoes
- No props, no furniture, no text, no graphics
- Realistic lighting, soft directional light, no artificial glow
- Avoid any AI-generated artifacts or exaggerated contrast

Composition:
- Square (1:1) ratio
- Pants occupy 75–80% of the frame
- Clean commercial thumbnail style suitable for product listing
      `;
      if (options?.faceOptions?.isWideFit) {
        finalPrompt += `\nIMPORTANT OVERRIDE:\n- Ensure wide silhouette is fully visible without cropping the outer leg lines.\n- Avoid perspective distortion. Keep the leg lines straight and wide.`;
      }
  } else if (preset === 'MZ_CAFE') {
      finalPrompt = `
[NanoBanana PRO MODE: K-MODERN CLEAN STREET]

**TASK:** Composite the subject into a clean, modern, and quiet Korean street background.

**SCENE COMPOSITION (CLEAN & MODERN):**
1.  **LOCATION:** A recently developed, trendy alley in Seoul (e.g., Seongsu-dong or tidy section of Yeonnam-dong).
2.  **ATMOSPHERE:** Quiet, peaceful, and clutter-free. No crowds, no trash, no complex signs.
3.  **GROUND:** Clean pavement/asphalt (light gray or warm tone). NO dirt, NO heavy cracks.
4.  **BACKGROUND ELEMENTS:**
    *   Modern minimal architecture (concrete, brick, glass).
    *   Soft natural sunlight (Golden Hour or Soft Overcast).
    *   Maybe a blurring trendy cafe facade in the distance.
    *   **NO TEXT / NO SIGNBOARDS** (Crucial).

**SUBJECT INTEGRATION:**
- Place the model naturally on the clean street.
- Realistic contact shadows on the pavement.
- Valid perspective matching the street depth.

**QUALITY:**
- Photorealistic, High Detail, 8K.
- Soft, flattering lighting for fashion.
      `;
  }

  // 2. Call API (Using Creation Strategy)
  const result = await generateContentSafe(finalPrompt, parts, { 
    taskType: 'CREATION',
    model: GEMINI_MODELS.IMAGE_GEN, // gemini-3-pro-image-preview
    config: {
        imageConfig: {
            aspectRatio: options?.aspectRatio || '1:1',
            imageSize: options?.resolution || '1K'
        }
    }
  });

  // Extract Image
  if (result.inlineData) return `data:${result.inlineData.mimeType};base64,${result.inlineData.data}`;
  throw new Error("No image generated by background replacement.");
};


/**
 * 2️⃣ Color Variation Service
 * Includes Vision Analysis (Color Extraction) + Text-to-Image Edit
 */
export const changeColorVariant = async (
  sourceProductImage: string,
  referenceColorImage: string,
  maskImage?: string
) => {
  // Step 1: Extract Color Description
  const descriptionPrompt = `
      Analyze this image and describe the dominant color or fabric finish in detail.
      Focus ONLY on the color pigment and texture appearance.
      Example Output: "Deep indigo blue with a slight faded denim texture", "Matte olive green", "Metallic silver".
      Keep it concise (under 10 words).
  `;
  
  console.log("🎨 Extracting Color Description...");
  const analysisResult = await generateContentSafe(descriptionPrompt, [fileToPart(referenceColorImage)], {
    taskType: 'TEXT',
    model: GEMINI_MODELS.HIGH_QUALITY 
  });
  
  const targetColorDesc = analysisResult.text;
  if (!targetColorDesc) throw new Error("Failed to extract color description.");
  console.log(`🎨 Extracted: "${targetColorDesc}"`);

  // Step 2: Apply Variation
  const applyPrompt = `
      TASK: Recolor the clothing item in the source image based on the reference color.
      TARGET COLOR: ${targetColorDesc}

      CRITICAL INSTRUCTION (DO NOT IGNORE):
      1. **EXECUTE THE EDIT DIRECTLY.** Do not describe the edit. Do not output JSON.
      2. **OUTPUT ONLY THE IMAGE.** I do not need any text explanation.
      3. **NO PLAN, NO THOUGHTS.** Just return the pixel result immediately.

      CRITICAL CONSTRAINTS (TEXTURE LOCK):
      1. **PRESERVE GEOMETRY:** Do NOT redraw or change the shape of the clothing.
      2. **PRESERVE TEXTURE:** Maintain the original fabric texture (corduroy, denim, etc.) exactly.
      3. **PRESERVE LIGHTING:** Keep original shadows. Only change the pigment.
  `;

  const editParts = [fileToPart(sourceProductImage)];
  if (maskImage && maskImage.length > 100) {
      editParts.push(fileToPart(maskImage));
  }

  console.log("🖌️ Applying Editor with 1.5 Pro...");
  const editResult = await generateContentSafe(applyPrompt, editParts, {
      taskType: 'EDIT',
      model: GEMINI_MODELS.EDIT_STABLE // 1.5 Pro
  });

  if (editResult.inlineData) return `data:${editResult.inlineData.mimeType};base64,${editResult.inlineData.data}`;
  throw new Error("No image generated by color variation.");
};


/**
 * 3️⃣ Magic Eraser Service
 */
export const magicEraser = async (
  originalImage: string,
  maskImage: string,
  prompt?: string
) => {
  let finalPrompt = "";
  if (prompt && prompt.trim() !== "") {
    finalPrompt = `
[NanoBanana PRO MODE: MAGIC EDITOR]
**TASK:** Edit the image based on the user request and the provided mask.
**USER REQUEST:** "${prompt}"
**INSTRUCTIONS:**
- Modify ONLY the masked area to match the request.
- Blend seamlessly with the surrounding pixels.
- Use the mask as a guide for the area to change.
    `;
  } else {
    finalPrompt = `
[NanoBanana PRO MODE: MAGIC ERASER]
**TASK:** Completely REMOVE the object covered by the white mask area.
**CRITICAL:** Seamlessly INPAINT and reconstruct the area by extending the surrounding background textures, lighting, and shadows. 
**INSTRUCTIONS:**
- The result must look perfectly natural, as if the object was never there.
- Do NOT fill with solid color or artifacts. 
- Blend perfectly with the environment (lighting, texture, perspective).
    `;
  }

  const result = await generateContentSafe(finalPrompt, [
      fileToPart(originalImage),
      fileToPart(maskImage)
  ], {
      taskType: 'EDIT',
      model: GEMINI_MODELS.EDIT_STABLE
  });

  if (result.inlineData) return `data:${result.inlineData.mimeType};base64,${result.inlineData.data}`;
  throw new Error("No image generated by magic eraser.");
};

// --- VARIATIONS & ADVANCED GENERATION ---

export const BACKGROUND_THEME_VARIATIONS: Record<string, string[]> = {
  'MZ_CAFE': [
    // Option 1: Warm Urban Cafe
    `A candid street style photograph in front of a sunlit brick cafe in Seoul.
   CRITICAL: Integrate the subject into the warm afternoon sunlight.
   Add realistic soft shadows cast by the model onto the pavement.
   The model's pose is naturally adjusted to look relaxed in this setting.
   The corduroy texture should glow subtly in the warm light.`,

    // Option 2: Bright Modern Street
    `A bright, clean, modern city sidewalk with concrete architecture and green plants.
   CRITICAL: Use bright, diffused daylight (soft overcast) to clearly highlight the product details.
   The lighting on the model must match the bright, clean background perfectly.
   Slightly naturalized standing pose. Minimalist and high-end feel.`,

    // Option 3: Soft Nature Light (Park)
    `A golden hour photograph on a path in a beautiful urban park with blurred trees.
   CRITICAL: Dramatic golden backlighting (rim light) on the model's jacket and hair.
   Long, soft shadows cast on the ground. The overall mood is warm, inviting, and aspirational.
   Subject looks comfortably integrated into the natural environment.`,

    // Option 4: Hip Industrial
    `A trendy industrial street corner with grey concrete and weathered metal textures.
   CRITICAL: Realistic daylight with a slight cool tone.
   Strong, realistic contact shadows under the boots to ground the subject.
   The model's pose is slightly more dynamic to match the hip environment.
   Sharp focus on the clothing texture against the rough background.`
  ],
  'BASIC_STUDIO': [
    'clean minimal off-white infinity wall, soft diffused shadow, e-commerce standard',
    'warm beige plaster wall, dried flower shadow accent, cozy boutique vibe',
    'cool grey concrete floor and wall, high fashion editorial lighting',
    'deep navy solid background, dramatic side lighting, premium brand feel'
  ]
};

export const generatePoseVariation = async (
  currentResultImage: string,
  promptModifier: string = "Shift weight slightly, looking casually to the side."
): Promise<string> => {
    const variationPrompt = `
      TASK: Generate a photorealistic variation of the provided input image.
      
      CRITICAL CONSTRAINTS (DO NOT CHANGE):
      1. **BACKGROUND LOCK:** The background environment, location, time of day, and overall lighting atmosphere MUST remain exactly the same as the input image. Do NOT revert to a studio setting.
      2. **CLOTHING LOCK:** The outfit must remain perfectly identical.

      ACTIONS (CHANGE):
      1. **POSE Variation:** Change the model's pose naturally based on this instruction: "${promptModifier}". The pose should feel relaxed and candid, suitable for a fashion lookbook detail shot.
      2. **DYNAMIC SHADOWS:** Realistic contact shadows and cast shadows on the ground must be regenerated to match the NEW pose, consistent with the scene's original light source.
      3. **COMPOSITION:** A very slight shift in camera angle or perspective is allowed to enhance realism, as long as the location is clearly the same.
    `;

    console.log("🎬 Generating Pose Variation with Background Lock...");

    const result = await generateContentSafe(variationPrompt, [fileToPart(currentResultImage)], {
        taskType: 'EDIT',
        model: GEMINI_MODELS.EDIT_STABLE
    });

    if (result.inlineData) return `data:${result.inlineData.mimeType};base64,${result.inlineData.data}`;
    throw new Error("No image data returned from AI (Pose Variation).");
};

export const generateBackgroundVariations = async (
  baseImage: string,
  themeKey: 'MZ_CAFE' | 'BASIC_STUDIO',
  resolution: Resolution,
  aspectRatio: AspectRatio,
  faceOptions: any,
  signal?: AbortSignal,
  onStatusUpdate?: (message: string) => void,
  options?: any
): Promise<{ index: number; url: string | null; error?: string }[]> => {
  
  const variations = BACKGROUND_THEME_VARIATIONS[themeKey] || [];
  
  // Helper for single generation
  const generateSingleVariation = async (prompt: string, index: number) => {
      try {
          const resultUrl = await replaceBackground(baseImage, null, prompt, {
              resolution,
              aspectRatio,
              faceOptions: { ...faceOptions, preset: themeKey }, // Pass preset context if needed
              modelPersona: options?.modelPersona,
              styleReference: options?.styleReference
          });
          return { index, url: resultUrl };
      } catch (err: any) {
          console.error(`Variation ${index} failed:`, err);
          return { index, url: null, error: err.message };
      }
  };

  // Chunking Logic
  const results: { index: number; url: string | null; error?: string }[] = [];
  const chunkSize = 2;

  for (let i = 0; i < variations.length; i += chunkSize) {
    if (signal?.aborted) break;

    const chunk = variations.slice(i, i + chunkSize);
    onStatusUpdate?.(`시안 생성 중 (${i + 1}~${Math.min(i + chunkSize, variations.length)}/${variations.length})... ⚡️`);

    const chunkResults = await Promise.all(
      chunk.map((prompt, idx) => generateSingleVariation(prompt, i + idx))
    );
    results.push(...chunkResults);

    if (i + chunkSize < variations.length) {
      if (signal?.aborted) break;
      await new Promise(resolve => setTimeout(resolve, 500));
    }
  }

  onStatusUpdate?.("4가지 시안 생성 완료! 🎉");
  return results;
};


// --- BENCHMARK (VIBE-COPY) SERVICE ---

// --- BENCHMARK (VIBE-COPY) SERVICE ---

/**
 * 🔍 Analyze Reference Image for Vibe Extraction
 * Uses Gemini Vision to reverse-engineer the lighting, environment, and style.
 */
export const analyzeBenchmarkImage = async (
  referenceImage: string
): Promise<BenchmarkAnalysisResult> => {
  const prompt = `
    Analyze this fashion thumbnail image for "Vibe Copy" purposes.
    I need to recreate this exact aesthetic for another product.
    
    Extract the following visual attributes in JSON format:
    
    1. Lighting:
       - Type: 'Natural' | 'Studio' | 'Flash' | 'Neon' | 'Mixed'
       - Direction: e.g., "Side right", "Backlit", "Frontal Flash"
       - Quality: e.g., "Hard shadows", "Soft diffused", "Cinematic"
       
    2. Environment:
       - Location: Precise description (e.g., "Seoul Seongsu-dong cafe street", "Minimal white studio")
       - Props: Any visible background elements (e.g., "Steel chair", "Plants", "Traffic cone"). If none, return empty array.
       - Surface: Ground/Wall texture (e.g., "Cracked asphalt", "Plaster wall")
       
    3. Technical:
       - Vibe Keywords: 3-5 adjectives (e.g., "Raw", "Gritty", "High-fashion", "Retro"). MUST be an array of strings.
       - Color Grading: Describe the post-processing tone (e.g., "Desaturated cool glossy", "Warm vintage")
       - Composition: Camera angle and framing (e.g., "Low angle", "Wide shot")

    Return ONLY the JSON object. No markdown formatting.
  `;

  const result = await generateContentSafe(prompt, [fileToPart(referenceImage)], {
    taskType: 'TEXT',
    model: GEMINI_MODELS.HIGH_QUALITY, // Use Logic Pro for detailed analysis
    config: { responseMimeType: "application/json" }
  });

  try {
    const json = JSON.parse(result.text || '{}');
    // Validation / Fallback
    if (!json.vibe_keywords) json.vibe_keywords = ["Trendy", "Clean"];
    if (!Array.isArray(json.vibe_keywords)) json.vibe_keywords = [json.vibe_keywords];
    if (!json.lighting) json.lighting = { type: 'Studio', direction: 'Front', quality: 'Soft' };
    if (!json.environment) json.environment = { location: 'Minimal Studio', props: [], surface: 'Smooth' };

    return json as BenchmarkAnalysisResult;
  } catch (e) {
    console.error("Benchmark Analysis Parse Error:", e);
    // Fallback object instead of throwing
    return {
        lighting: { type: 'Studio', direction: 'Front', quality: 'Soft' },
        environment: { location: 'Modern Studio', props: [], surface: 'Clean' },
        vibe_keywords: ['Simple', 'Clean'],
        color_grading: 'Natural',
        composition: 'Eye Level'
    };
  }
};

/**
 * 🖌️ Apply Benchmark Style (Vibe Transfer)
 * synthesizing the user's product into the analyzed "Vibe".
 */
export const applyBenchmarkStyle = async (
  productImage: string,
  analysis: BenchmarkAnalysisResult,
  resolution: Resolution = '1K',
  aspectRatio: AspectRatio = '1:1'
): Promise<string> => {
  
  const keywords = Array.isArray(analysis.vibe_keywords) ? analysis.vibe_keywords.join(', ') : 'High Quality';
  const loc = analysis.environment?.location || 'Studio';
  const surface = analysis.environment?.surface || 'Clean floor';
  const lightType = analysis.lighting?.type || 'Natural';
  const lightDir = analysis.lighting?.direction || 'Soft';
  const lightQual = analysis.lighting?.quality || 'Good';

  // Construct a High-Fidelity Prompt based on Analysis
  const vibePrompt = `
    [NanoBanana PRO: VIBE TRANSFER MODE]
    
    **TASK**: Composite the input product image into a new background that PERFECTLY MATCHES the following "Vibe Reference".
    
    **TARGET AESTHETIC (STRICTLY FOLLOW):**
    - **VIBE**: ${keywords}.
    - **LOCATION**: ${loc}. Surface: ${surface}.
    - **LIGHTING**: ${lightType}, ${lightDir} direction, ${lightQual}.
    - **COLOR TONE**: ${analysis.color_grading || 'Natural'}.
    - **COMPOSITION**: ${analysis.composition || 'Standard'}.
    
    **PRODUCT INTEGRATION:**
    - Place the product naturally in this environment.
    - **CRITICAL**: Apply the specific lighting (${lightType}) onto the product so it looks like it was photographed there.
    - Cast realistic shadows consistent with the ${lightDir} light source.
    - If "Flash" lighting is detected, add a slight hard flash falloff to the background.
    
    **QUALITY:**
    - Photorealistic, 8K, Commercial Fashion Photography.
    - Texture of the product must remain sharp (Texture Lock).
  `;

  const result = await generateContentSafe(vibePrompt, [fileToPart(productImage)], {
    taskType: 'CREATION',
    model: GEMINI_MODELS.IMAGE_GEN,
    config: {
      imageConfig: {
        aspectRatio,
        imageSize: resolution
      }
    }
  });

  if (result.inlineData) return `data:${result.inlineData.mimeType};base64,${result.inlineData.data}`;
  throw new Error("No image generated by benchmark style.");
};
